# Conversion of Rijksdriehoek to WGS84 coordinates 
Or the other way around

In [8]:
# Load data
import pandas as pd
df = pd.read_csv('../data/eval_spatialCoverageText.csv')

In [9]:
df

,id,title,dsDescriptionValues,dansSpatialCoverageText,dansSpatialPoints,dansSpatialSchemes,pred_coordinate
0,10.17026/dans-z2t-fr88,Beerseweg 6 Oirschot,KSP Archeologie heeft een archeologisch bureau...,"['Oirschot', 'Noord-Brabant']","148651, 389591",RD (in m.),"[(51.488961599999996, 5.300594979407693), (51...."
1,10.17026/dans-xx7-w66k,NABO - locatie Beesel,Om het aantal incidenten op overwegen te vermi...,"['Beesel', 'Gemeente Beesel', 'Limburg']","202395, 364385",RD (in m.),"[(51.26998845, 6.073401860697201), 'NOT FOUND:..."
2,10.17026/dans-xdh-uzt5,"Bloemendaal, Brederodelaan 34 Gemeente Bloemen...",In februari 2015 is een archeologisch vooronde...,"['Brederodelaan 34', 'Bloemendaal', 'Gemeente ...","102990, 492811",RD (in m.),"[(52.2699055, 6.135358), (52.3742917, 4.591534..."
3,10.17026/dans-zeu-pe5h,"Locatie 'Dr. van Noortstraat 6' te Lienden, ge...",onderzoeksrapport,"['Dr. van Noortstraat', 'Nederland', 'Buren', ...","164000, 439847",RD (in m.),"[(52.095804351429294, 4.47140172755453), (52.2..."
4,10.17026/dans-z3c-p6t9,"bbbley 1, 2, 3 en 4 (Leyweg)",4 projecten samengevoegd: Leyweg 1412-1482 bor...,"['Den Haag', ""'s-Gravenhage"", 'Zuid-Holland', ...","78919, 451961",RD (in m.),"[(52.07494555, 4.2696802205364515), (52.079983..."
...,...,...,...,...,...,...,...
213,10.17026/AR/3NN2CO,"Janninkcomplex Haaksbergerstraat 147, Enschede.",Onderzoek naar de uit 1900-1901 daterende kato...,"['Haaksbergerstraat 147, 7513 EL Enschede', 'R...","6.88671, 52.21384",longitude/latitude (degrees),"[(52.213835, 6.8866696), 'NOT FOUND: Rijksmonu..."
214,10.17026/dans-zxj-k3yb,Archeologisch bureauonderzoek Ugchelseweg 78 t...,Uit het bureauonderzoek blijkt dat er terreind...,"['33B', 'Ugchelseweg 78', 'Apeldoorn', 'Gelder...","192747, 466636",RD (in m.),"[(-22.03348025, -59.9783108380642), (52.187238..."
215,10.17026/dans-zkw-qwn8,Westdorpe Molenstraat. Gemeente Terneuzen.,Op basis van de beschikbare informatie over de...,"['Zeeland', 'Gemeente Terneuzen', 'Westdorpe',...","47235, 360067",RD (in m.),"[(51.4162975, 3.7028061), (51.331782399999994,..."
216,10.17026/dans-zt5-ayk6,Gameren 't Slot' (gemeente Zaltbommel),onderzoeksrapport,"['t Slot', 'Nederland', 'Gameren', 'Gelderland...","142220, 423710",RD (in m.),"[(52.7522238, 5.0759089), (52.2434979, 5.63432..."
217,10.17026/dans-xqj-rwu2,"Recreatieplas Cattenbroek, gemeente Woerden",RAAP Archeologisch Adviesbureau heeft op 6 en ...,"['31G', 'Recreatieplas Cattenbroek', 'Woerden'...","123361, 455639",RD (in m.),"[(13.664171150000001, -89.25022706949764), (52..."

In [11]:
# Extract coordinates 
all_coords = df.dansSpatialPoints.tolist()
all_coords

['148651, 389591',
 '202395, 364385',
 '102990, 492811',
 '164000, 439847',
 '78919, 451961',
 '188978, 432902',
 '204.160, 476.203',
 '104346, 470037',
 '124525, 562325',
 '220700, 431750',
 '253481, 593196',
 '182213, 430572',
 '159965, 371231; 159900, 371210',
 '96409, 398074',
 '237219, 535959',
 '233469, 582729',
 '130855, 407070',
 '128970, 467727',
 'None,None',
 '76989, 455005',
 '167808, 438460',
 '104750, 420500',
 '242930, 529067',
 '154168, 391902',
 '5.12299, 52.23198',
 '171850, 482740',
 '90745, 470767',
 '200816, 437728',
 '94350, 396798',
 '131432, 507678',
 '235355, 559696',
 '78059, 439586',
 '135291, 393324',
 '60131, 384988',
 '161475, 470570',
 '167044, 366588; 166865, 365969; 166619, 366172; 166559, 366251',
 '150072, 482650; 151200, 483141; 149792, 484626',
 '43790, 361068; 43803, 361020',
 '170050, 461399',
 '107072, 502794',
 '151304, 413434',
 '110891, 499507',
 '88333, 468600; 88860, 468363',
 '29043, 386309',
 '181890, 487432',
 'None,None',
 '251471, 600738',
 '80597, 457113',
 '208989, 516068',
 '193.126, 444.450',
 '201500, 433285',
 '250479, 445910',
 '15367, 370560',
 '160045, 442519',
 '104903, 430743',
 '82516, 399447; 82565, 399902',
 '174226, 447755',
 '193861, 392590',
 '85117, 459937',
 '211709, 465424',
 '122823, 493915',
 '203400, 495000',
 '200818, 497446',
 '159304, 370147',
 'None,None',
 'None,None',
 '253241, 564581',
 '84290, 436730',
 '85310, 437350',
 '77601, 437359',
 '125550, 545200',
 '98948, 398426',
 '200712, 385269',
 '215704, 444054',
 '108040, 509729',
 '82020, 458058; 82112, 458077; 82083, 458018; 82132, 458036',
 '215617, 471756',
 '106107, 425274',
 '118550, 469100',
 '194315, 469897',
 '204835, 430375',
 '118120, 407015',
 '251366, 598897',
 '186774, 427619',
 '176324, 401041',
 '138720, 379930',
 '199851, 498987',
 '191841, 572845',
 '144247, 440766',
 '95353, 432662',
 '155210, 463248',
 '206566, 438353',
 '229370, 577400',
 '148082, 463671',
 '154628, 471475; 154562, 471540',
 '197925, 441125',
 '224109, 437922',
 '208228, 516193',
 '54900, 425370',
 '70111, 427421',
 '209102, 376455',
 '263134, 576670',
 '194756, 593832',
 '85700, 461200',
 '184559, 332649',
 '106926, 400100',
 '166634, 373115',
 '203416, 501258',
 '110838, 515826',
 '203040, 570190',
 'None,None',
 '6.27683, 52.10022',
 '139254, 459352',
 '187721, 496121',
 '168533, 479976',
 '84265, 427872',
 '216457, 483353',
 '215315, 581464',
 '125350, 529750',
 '133330, 483368',
 'None,None',
 '188196, 428598',
 '229377, 582023',
 '182117, 412069',
 '171052, 384116',
 '89440, 468756',
 '243400, 480625',
 '92601, 445797',
 '196608, 388287',
 '105520, 394361',
 '133190, 450183',
 '159516, 373330',
 '187130, 432570',
 '194352, 469737',
 '241992, 530577',
 '235042, 556477',
 '177708, 315310',
 '242913, 588918',
 '115688, 400222',
 '149106, 445848',
 '258100, 471310',
 '211278, 459080',
 '148569, 433003',
 '207859, 473689',
 '187297, 363032',
 '143265, 483008',
 '135019, 403888',
 '122589, 406181',
 '143960, 487025',
 '83681, 452201',
 'None,None',
 '181939, 429717',
 '155208, 463575',
 '235883, 503428',
 '181024, 516741',
 '258043, 520147',
 '5.86939, 50.99986',
 '102439, 441967',
 '256765, 481626',
 '95020, 473140',
 '135070, 395959',
 'None,None',
 '186458, 327647',
 'None,None',
 '180055, 379481; 180128, 379481; 180055, 379552; 180128, 379552',
 '167565, 461030',
 '140838, 427975',
 '149410, 390265',
 '188670, 430984',
 '132874, 481443',
 '167103, 420347',
 '238670, 579800',
 '111763, 515948',
 '186930, 352906',
 '125548, 432534',
 'None,None',
 '149980, 447180',
 '240487, 552106',
 '206109, 445349',
 '176096, 432382; 177019, 430718',
 '179727, 367553; 179720, 367477',
 '5.98048, 50.88799',
 '172701, 583896',
 '223564, 454321',
 '149390, 411215',
 '148108, 523887',
 '209460, 376060',
 '143879, 440887',
 '197290, 314060',
 'None,None',
 '57460, 371293',
 '112329, 538954',
 '19331, 363771',
 'None,None',
 '202739, 440196',
 '239473, 453680',
 '214976, 435815',
 '51320, 389285',
 '249692, 593468',
 '104885, 387325',
 '235760, 570755',
 '92.810, 457.010',
 '93310, 462138',
 '75180, 453960',
 '221012, 436871',
 '63318, 381901',
 '142196, 452726',
 '144800, 476580',
 '240549, 455110',
 '136729, 527201',
 '115222, 472509; 115211, 472491',
 '216332, 520721',
 '35821, 396713',
 '6.88671, 52.21384',
 '192747, 466636',
 '47235, 360067',
 '142220, 423710',
 '123361, 455639']

In [60]:
test = all_coords[:5]

['148651, 389591',
 '202395, 364385',
 '102990, 492811',
 '164000, 439847',
 '78919, 451961']

In [103]:
from scripts.convert_rd_to_wpg84 import query_api


# Clean responses, turn into dictionary
responses = []
for pair in test:
    coord1, coord2 = pair.split(',')
    coord1 = coord1.strip()
    coord2 = coord2.strip()
    
    response = query_api(coord1, coord2)

    responses.append(response)

In [104]:
responses

[{'WGS84': '51.495314,5.295777', 'RD': '148651,389591'},
 {'WGS84': '51.266798,6.066296', 'RD': '202395,364385'},
 {'WGS84': '52.420641,4.622645', 'RD': '102990,492811'},
 {'WGS84': '51.947000,5.518109', 'RD': '164000,439847'},
 {'WGS84': '52.050734,4.278031', 'RD': '78919,451961'}]

In [107]:
# Convert dansSpatialPoints to WPG84
dansWPG85 = []
for item in responses:
    dansWPG85.append(item['WGS84'])
dansWPG85

['51.495314,5.295777',
 '51.266798,6.066296',
 '52.420641,4.622645',
 '51.947000,5.518109',
 '52.050734,4.278031']